-- Venue sample counts + split rates for bounded TeamProfile calibration
ALTER TABLE "TeamProfile" ADD COLUMN IF NOT EXISTS "homeMatchesCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "TeamProfile" ADD COLUMN IF NOT EXISTS "awayMatchesCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "TeamProfile" ADD COLUMN IF NOT EXISTS "over15GoalsRateHome" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "TeamProfile" ADD COLUMN IF NOT EXISTS "over15GoalsRateAway" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "TeamProfile" ADD COLUMN IF NOT EXISTS "cleanSheetRateHome" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "TeamProfile" ADD COLUMN IF NOT EXISTS "cleanSheetRateAway" DOUBLE PRECISION NOT NULL DEFAULT 0;
